---
- name: Install conda
  block:
  - name: Check variables
    ansible.builtin.assert:
      that:
        - username is defined
        - homedir is defined

  - name: Check miniconda
    ansible.builtin.stat:
      path: "{{ homedir }}/local/miniconda"
    register: conda_stat

    # Block to become user
  - name: Become the user
    become: true
    become_user: "{{ username }}"
    block:

      # Block for actual conda install
      - name: Conda install block
        when: not conda_stat.stat.exists
        block:

          - name: Download miniconda
            ansible.builtin.get_url:
              url: "https://repo.anaconda.com/miniconda/\
                    Miniconda3-latest-Linux-x86_64.sh"
              dest: /tmp/miniconda.sh
              mode: '0700'
            register: mc_dl

          - name: Install miniconda
            ansible.builtin.command: >
              /tmp/miniconda.sh -b -p "{{ homedir }}/local/miniconda"
            when: mc_dl.status_code == 200
            register: mc_inst

          - name: Remove miniconda installer
            ansible.builtin.file:
              path: /tmp/miniconda.sh
              state: absent
            when: mc_dl.status_code == 200

          - name: Add miniconda to zshrc
            ansible.builtin.command: >
              "{{ homedir }}/local/miniconda/bin/conda init zsh"
            when: mc_inst.rc == 200

      - name: Pull Conda autocomplete
        ansible.builtin.git:    # noqa latest[git]
          repo: https://github.com/esc/conda-zsh-completion
          dest: "{{ homedir }}/local/src/conda-zsh-completion"

      - name: Add autocomplete to zsh - part 1
        ansible.builtin.lineinfile:
          dest: "{{ homedir }}/.zshrc"
          insertbefore: "^source \\$ZSH/oh-my-zsh.sh$"
          line: "fpath+={{ homedir }}/local/src/conda-zsh-completion"

      - name: Add autocomplete to zsh - part 2
        ansible.builtin.lineinfile:
          dest: "{{ homedir }}/.zshrc"
          insertafter: "^source \\$ZSH/oh-my-zsh.sh$"
          line: "compinit conda"
