- hosts: all
  tasks:
    - name: Check miniconda
      ansible.builtin.stat:
        path: {{ homedir }}/local/miniconda
      register: conda_stat

    # Block to become user
    - block:

      # Block for actual conda install
      - block:
        - name: Download miniconda
          ansible.builtin.get_url:
            url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
            dest: /tmp/miniconda.sh
            mode: '0700'

        - name: Install miniconda
          ansible.builtin.shell:
            cmd: /tmp/miniconda.sh -b -p {{ homedir }}/local/miniconda

        - name: Remove miniconda installer
          ansible.builtin.file:
            path: /tmp/miniconda.sh
            state: absent

        - name: Add miniconda to zshrc
          ansible.builtin.shell:
            cmd: conda init zsh

        when: not conda_stat.stat.exists
        # End conda install portion; still operating as the user

      - name: Pull Conda autocomplete
        ansible.builtin.git:
          repo: https://github.com/esc/conda-zsh-completion
          dest: {{ homedir }}/local/src/conda-zsh-completion

      - name: Add autocomplete to zsh - part 1
        ansible.builtin.lineinfile:
          dest: {{ homedir }}/.zshrc
          insertbefore: "^source \\$ZSH/oh-my-zsh.sh$"
          line: "fpath+={{ homedir }}/local/src/conda-zsh-completion"

      - name: Add autocomplete to zsh - part 2
        ansible.builtin.lineinfile:
          dest: {{ homedir }}/.zshrc
          insertafter: "^source \\$ZSH/oh-my-zsh.sh$"
          line: "compinit conda"

      become: yes
      become_user: {{ username }}
