---
- name: Begin local
  hosts: all
  tags: always
  become: true

  pre_tasks:
    # FIXME: We only support debian based distributions for now
    - name: Check distro
      tags: always
      ansible.builtin.assert:
        that:
          - ansible_distribution in ["Debian", "Ubuntu"]

    - name: Update base OS
      tags: always
      ansible.builtin.apt:
        upgrade: dist
        force_apt_get: true
        cache_valid_time: 3600
      changed_when: false

# Roles
- name: Define base role
  hosts: all
  tags: base
  become: true
  roles:
    - base

- name: Define dualboot role
  hosts: dualboot
  tags: dualboot
  become: true
  roles:
    - dualboot

- name: Define devel role
  hosts: devel
  tags: devel
  become: true
  roles:
    - devel

- name: Define docker role
  hosts: docker
  tags: docker
  become: true
  roles:
    - docker

- name: Define gui role
  hosts: gui
  tags: gui
  become: true
  roles:
    - gui

- name: Define rtlsdr role
  hosts: rtlsdr
  tags: rtlsdr
  roles:
    - rtlsdr

- name: Define server role
  hosts: server
  tags: server
  become: true
  roles:
    - server

# vim: ft=ansible
