---
- name: Setup NFS
  block:

  - name: Install NFS client software
    ansible.builtin.apt:
      name:
        - nfs-common
        - autofs
      state: latest   # noqa package-latest

  - name: Install backup.autofs
    ansible.builtin.copy:
      src: backup.autofs
      dest: /etc/auto.master.d/backup.autofs
      owner: root
      group: root
      mode: 0644

  - name: Add NFS lines to auto.nfs
    ansible.builtin.lineinfile:
      path: /etc/auto.nfs
      create: true
      owner: root
      group: root
      mode: 0644
      line: "{{ item.point }}    {{ server }}:{{ volume }}"
    loop: "{{ nfs_mounts }}"
